### ISSUE TITLE
undefined symbol: lxc_strerror 

### ISSUE THREAD

**Issue by Jafaral** [lxc/ruby-lxc#39]
Hi,

  I'm experimenting with this package but I keep getting this error:

$ruby test.rb 
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': /var/lib/gems/2.3.0/gems/ruby-lxc-1.2.1/lib/lxc/lxc.so: undefined symbol: lxc_strerror - /var/lib/gems/2.3.0/gems/ruby-lxc-1.2.1/lib/lxc/lxc.so (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/ruby-lxc-1.2.1/lib/lxc.rb:2:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from test.rb:1:in `<main>'

OUTPUT of nm:
$nm /var/lib/gems/2.3.0/gems/ruby-lxc-1.2.1/lib/lxc/lxc.so | grep lxc_str
       U lxc_strerror

obviously it is undefined in lxc.so and it is expected to be defined  at runtime. Who is supposed to define it? what am I missing ? 

Thanks in advanced for any help.

**Comment by Jafaral** [comment]
@andrenth Do you have any idea what is causing this?

**Comment by Jafaral** [comment]
I see this error message on two ubuntu 16.04 AMD64 desktop machines, but it works on Ubuntu 16.04 armhf after I switched to an ubuntu server from desktop version. The three machines have  the same lxc version (2.0.4), same ruby-lxc 1.2.1. The only difference is ruby version. The machine that I don't have problem with is running ruby 2.3.0 while all others are running 2.3.1p112 as I mentioned above.

**Comment by Jafaral** [comment]
My work around for now was to just declare a dummy lxc_strerror() function in lxc.so to avoid the undefined symbol issue.

**Comment by andrenth** [comment]
I've merged your pull request and released version 1.1.2. Sorry for the delay.
