### ISSUE TITLE
ruby-lxc broken by liblxc 4.0.4: undefined symbol: lxc_config_parse_arch

### ISSUE THREAD

**Issue by ganto** [lxc/ruby-lxc#45]
When checking if my various [LXC-related RPM packages](https://copr.fedorainfracloud.org/coprs/ganto/lxc3) with the latest Fedora version, I found that ruby-lxc is not working anymore. When trying to use it with the latest `lxc-4.0.4` I get the following error:
```
Traceback (most recent call last):
        2: from container.rb:1:in `<main>'
        1: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- lxc (LoadError)
        6: from container.rb:1:in `<main>'
        5: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:34:in `require'
        4: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
        3: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:130:in `require'
        2: from /usr/share/gems/gems/ruby-lxc-1.2.3/lib/lxc.rb:2:in `<top (required)>'
        1: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require': /usr/lib64/gems/ruby/ruby-lxc-1.2.3/lxc/lxc.so: undefined symbol: lxc_config_parse_arch - /usr/lib64/gems/ruby/ruby-lxc-1.2.3/lxc/lxc.so (LoadError)
```
I guess it was broken by commit [63c2a0b: confile: hide unnecessary symbols](https://github.com/lxc/lxc/commit/63c2a0bf06d5ddd7cbbc908ea1e403b69f4b6a0c).

Was this intended? Is ruby-lxc still supported?

**Comment by ganto** [comment]
@brauner Since you authored that commit can you maybe have a look?
